spring:
  application:
    name: bank-theft
  datasource:
    url: ${SPRING_DATASOURCE:jdbc:postgresql://localhost:5432/bank_theft}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  #kafka:
    #  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      #  consumer:
      #   auto-offset-reset: earliest
      #   enable-auto-commit: false              # ? Desliga commit autom?tico
      #   group-id: documents-analysis-group
      #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        #   properties:
        #      spring.json.trusted.packages: "br.com.picpay_user.dtos.documents,br.com.picpay_document.dtos"
        #     spring.json.type.mapping: br.com.picpay_user.dtos.documents.RequestDocuments:br.com.picpay_document.dtos.ConsumerCardAnalysis
    #     spring.json.value.default.type: br.com.picpay_document.dtos.ConsumerCardAnalysis
      #  listener:
    #   ack-mode: manual                       # ? Ativa acknowledgment manual

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'


public:
  key: classpath:public-key

server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: never

