spring:
  application:
    name: bank-document
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_document
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 30
      properties:
        spring.json.add.type.headers: false
        retry.backoff.ms: 5000

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'


public:
  key: classpath:public-key

server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: never
