spring:
  application:
   name: bank-user

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_user}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        retry.backoff.ms: 5000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'

resilience4j:
  circuitbreaker:
    instances:
      registerCB:
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slidingWindowSize: 5

public:
  key: classpath:public-key

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never